apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{ .namespace }}

resources:
  - externalsecret.yaml

helmCharts:
  - name: harbor
    repo: https://helm.goharbor.io
    releaseName: harbor
    namespace: {{ .namespace }}
    version: 1.16.0
    valuesFile: ./values.yaml
