apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{ .namespace }}

resources:
  - externalsecret.yaml

helmCharts:
  - name: dex
    repo: https://charts.dexidp.io
    releaseName: dex
    namespace: {{ .namespace }}
    version: 0.22.1
    valuesFile: ./values.yaml
