apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mobilizon-secrets
  namespace: mobilizon
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .eso.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: mobilizon-secrets
    creationPolicy: Owner
  data:
    - secretKey: MOBILIZON_INSTANCE_SECRET
      remoteRef:
        key: {{ .eso.remotePathPrefix }}/mobilizon
        property: instance-secret
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .eso.remotePathPrefix }}/mobilizon
        property: postgres-password
    - secretKey: SMTP_PASSWORD
      remoteRef:
        key: {{ .eso.remotePathPrefix }}/smtp
        property: password
