apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: stalwart-secrets
  namespace: stalwart
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .eso.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: stalwart-secrets
    creationPolicy: Owner
  data:
    - secretKey: STALWART_ADMIN_PASSWORD
      remoteRef:
        key: {{ .eso.remotePathPrefix }}/stalwart
        property: admin-password
    - secretKey: LDAP_BIND_PASSWORD
      remoteRef:
        key: {{ .eso.remotePathPrefix }}/dex
        property: ldap-bind-password
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: {{ .eso.remotePathPrefix }}/oidc
        property: stalwart
