apiVersion: v1
kind: Service
metadata:
  name: stalwart
  namespace: stalwart
  labels:
    app.kubernetes.io/name: stalwart
spec:
  selector:
    app.kubernetes.io/name: stalwart
  ports:
    - port: 25
      targetPort: smtp
      name: smtp
    - port: 465
      targetPort: smtps
      name: smtps
    - port: 587
      targetPort: submission
      name: submission
    - port: 993
      targetPort: imaps
      name: imaps
    - port: 8080
      targetPort: http
      name: http
