apiVersion: v1
kind: Service
metadata:
  name: mobilizon-postgres
  namespace: mobilizon
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: mobilizon
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: mobilizon
  ports:
    - port: 5432
      targetPort: 5432
