apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{ .namespace }}

resources:
  - cluster-secret-store.yaml

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    releaseName: external-secrets
    namespace: {{ .namespace }}
    version: 0.12.1
    valuesFile: ./values.yaml
