apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: forgejo-secrets
  namespace: forgejo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .eso.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: forgejo-secrets
    creationPolicy: Owner
  data:
    - secretKey: SECRET_KEY
      remoteRef:
        key: {{ .eso.remotePathPrefix }}/forgejo
        property: secret-key
    - secretKey: INTERNAL_TOKEN
      remoteRef:
        key: {{ .eso.remotePathPrefix }}/forgejo
        property: internal-token
    - secretKey: DB_PASSWD
      remoteRef:
        key: {{ .eso.remotePathPrefix }}/forgejo
        property: postgres-password
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .eso.remotePathPrefix }}/forgejo
        property: postgres-password
    - secretKey: MAILER_PASSWD
      remoteRef:
        key: {{ .eso.remotePathPrefix }}/smtp
        property: password
