apiVersion: v1
kind: Service
metadata:
  name: forgejo
  namespace: forgejo
  labels:
    app.kubernetes.io/name: forgejo
spec:
  selector:
    app.kubernetes.io/name: forgejo
  ports:
    - port: 3000
      targetPort: http
      name: http
    - port: 22
      targetPort: ssh
      name: ssh
