apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stalwart
  namespace: stalwart
  annotations:
    cert-manager.io/cluster-issuer: {{ .certIssuer }}
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  ingressClassName: {{ .ingressClassName }}
  tls:
    - hosts:
        - {{ .subdomains.stalwart }}.{{ .domain }}
      secretName: stalwart-tls
  rules:
    - host: {{ .subdomains.stalwart }}.{{ .domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stalwart
                port:
                  number: 8080
