apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stalwart-data
  namespace: stalwart
  labels:
    app.kubernetes.io/name: stalwart
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .storageClass }}
  resources:
    requests:
      storage: {{ .storage.stalwart }}
