apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ocis-secrets
  namespace: ocis
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .eso.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: ocis-secrets
    creationPolicy: Owner
  data:
    - secretKey: OCIS_MACHINE_AUTH_API_KEY
      remoteRef:
        key: {{ .eso.remotePathPrefix }}/ocis
        property: machine-auth-api-key
    - secretKey: OCIS_TRANSFER_SECRET
      remoteRef:
        key: {{ .eso.remotePathPrefix }}/ocis
        property: transfer-secret
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: {{ .eso.remotePathPrefix }}/oidc
        property: ocis
