apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ocis-data
  namespace: ocis
  labels:
    app.kubernetes.io/name: ocis
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .storageClass }}
  resources:
    requests:
      storage: {{ .storage.ocis }}
