apiVersion: v1
kind: Service
metadata:
  name: ocis
  namespace: ocis
  labels:
    app.kubernetes.io/name: ocis
spec:
  selector:
    app.kubernetes.io/name: ocis
  ports:
    - port: 9200
      targetPort: http
      name: http
