apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paperless
  namespace: paperless
  annotations:
    cert-manager.io/cluster-issuer: {{ .certIssuer }}
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  ingressClassName: {{ .ingressClassName }}
  tls:
    - hosts:
        - {{ .subdomains.paperless }}.{{ .domain }}
      secretName: paperless-tls
  rules:
    - host: {{ .subdomains.paperless }}.{{ .domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: paperless
                port:
                  number: 8000
