apiVersion: v1
kind: Service
metadata:
  name: paperless-redis
  namespace: paperless
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: paperless
spec:
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: paperless
  ports:
    - port: 6379
      targetPort: 6379
