apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pixelfed-postgres
  namespace: pixelfed
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: pixelfed
spec:
  serviceName: pixelfed-postgres
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
      app.kubernetes.io/part-of: pixelfed
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/part-of: pixelfed
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: pixelfed
            - name: POSTGRES_DB
              value: pixelfed
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pixelfed-secrets
                  key: DB_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .storageClass }}
        resources:
          requests:
            storage: {{ .storage.postgres }}
