apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless-secrets
  namespace: paperless
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .eso.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: paperless-secrets
    creationPolicy: Owner
  data:
    - secretKey: PAPERLESS_SECRET_KEY
      remoteRef:
        key: {{ .eso.remotePathPrefix }}/paperless
        property: secret-key
    - secretKey: PAPERLESS_DBPASS
      remoteRef:
        key: {{ .eso.remotePathPrefix }}/paperless
        property: postgres-password
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: {{ .eso.remotePathPrefix }}/paperless
        property: postgres-password
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: {{ .eso.remotePathPrefix }}/paperless
        property: redis-password
    - secretKey: PAPERLESS_EMAIL_HOST_PASSWORD
      remoteRef:
        key: {{ .eso.remotePathPrefix }}/smtp
        property: password
