apiVersion: v1
kind: Service
metadata:
  name: paperless-postgres
  namespace: paperless
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: paperless
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: paperless
  ports:
    - port: 5432
      targetPort: 5432
