apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/namespace.yaml
  - manifests/configmap.yaml
  - manifests/externalsecret.yaml
  - manifests/pvc.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/ingress.yaml
  - manifests/postgres-statefulset.yaml
  - manifests/postgres-service.yaml
