apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lldap-data
  namespace: lldap
  labels:
    app.kubernetes.io/name: lldap
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .storageClass }}
  resources:
    requests:
      storage: {{ .storage.lldap }}
