apiVersion: v1
kind: Service
metadata:
  name: lldap
  namespace: lldap
  labels:
    app.kubernetes.io/name: lldap
spec:
  selector:
    app.kubernetes.io/name: lldap
  ports:
    - name: ldap
      port: 3890
      targetPort: ldap
    - name: web
      port: 17170
      targetPort: web
