apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: lldap-secrets
  namespace: lldap
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .eso.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: lldap-secrets
    creationPolicy: Owner
  data:
    - secretKey: LLDAP_LDAP_USER_PASS
      remoteRef:
        key: {{ .eso.remotePathPrefix }}/lldap
        property: admin-password
    - secretKey: LLDAP_JWT_SECRET
      remoteRef:
        key: {{ .eso.remotePathPrefix }}/lldap
        property: jwt-secret
