apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{ .namespace }}

resources:
  - externalsecret.yaml

helmCharts:
  - name: minio
    repo: https://charts.min.io/
    releaseName: minio
    namespace: {{ .namespace }}
    version: 5.4.0
    valuesFile: ./values.yaml
