apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{ .namespace }}

resources:
  - externalsecret.yaml

helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    releaseName: argocd
    namespace: {{ .namespace }}
    version: 7.7.11
    valuesFile: ./values.yaml
