apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pixelfed-secrets
  namespace: pixelfed
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .eso.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: pixelfed-secrets
    creationPolicy: Owner
  data:
    - secretKey: APP_KEY
      remoteRef:
        key: {{ .eso.remotePathPrefix }}/pixelfed
        property: app-key
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .eso.remotePathPrefix }}/pixelfed
        property: postgres-password
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: {{ .eso.remotePathPrefix }}/pixelfed
        property: redis-password
    - secretKey: MAIL_PASSWORD
      remoteRef:
        key: {{ .eso.remotePathPrefix }}/smtp
        property: password
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: {{ .eso.remotePathPrefix }}/oidc
        property: pixelfed
