apiVersion: v1
kind: Service
metadata:
  name: pixelfed-postgres
  namespace: pixelfed
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: pixelfed
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: pixelfed
  ports:
    - port: 5432
      targetPort: 5432
