apiVersion: v1
kind: Service
metadata:
  name: pixelfed
  namespace: pixelfed
  labels:
    app.kubernetes.io/name: pixelfed
spec:
  selector:
    app.kubernetes.io/name: pixelfed
  ports:
    - port: 80
      targetPort: http
      name: http
