apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: {{ .namespace }}

resources:
  - element-web.yaml
  - externalsecret.yaml

helmCharts:
  - name: matrix-synapse
    repo: https://ananace.gitlab.io/charts
    releaseName: synapse
    namespace: {{ .namespace }}
    version: 3.12.21
    valuesFile: ./values.yaml
