apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests/namespace.yaml
  - manifests/externalsecret.yaml
  - manifests/pvc.yaml
  - manifests/server-deployment.yaml
  - manifests/server-service.yaml
  - manifests/server-ingress.yaml
  - manifests/agent-deployment.yaml
  - manifests/agent-serviceaccount.yaml
