apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: woodpecker-data
  namespace: woodpecker
  labels:
    app.kubernetes.io/name: woodpecker
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .storageClass }}
  resources:
    requests:
      storage: {{ .storage.woodpecker }}
