apiVersion: v1
kind: Service
metadata:
  name: woodpecker-server
  namespace: woodpecker
  labels:
    app.kubernetes.io/name: woodpecker
    app.kubernetes.io/component: server
spec:
  selector:
    app.kubernetes.io/name: woodpecker
    app.kubernetes.io/component: server
  ports:
    - port: 8000
      targetPort: http
      name: http
    - port: 9000
      targetPort: grpc
      name: grpc
