apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: woodpecker-secrets
  namespace: woodpecker
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .eso.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: woodpecker-secrets
    creationPolicy: Owner
  data:
    - secretKey: WOODPECKER_AGENT_SECRET
      remoteRef:
        key: {{ .eso.remotePathPrefix }}/woodpecker
        property: agent-secret
    - secretKey: WOODPECKER_GITEA_CLIENT
      remoteRef:
        key: {{ .eso.remotePathPrefix }}/woodpecker
        property: forgejo-client-id
    - secretKey: WOODPECKER_GITEA_SECRET
      remoteRef:
        key: {{ .eso.remotePathPrefix }}/woodpecker
        property: forgejo-client-secret
